* Replaced locally stored ginger-php library on composer library inst…
emspay/ems-online-prestashop-1.6 pull request #5
Opened 2020-09-07 13:54 UTC by LeasoftKonstantinShapoval

…aller.

2020-09-07 14:40 UTC, tiutiunnykleasoft approved these changes
OK.

2020-09-08 11:36 UTC, LeasoftKonstantinShapoval commented
Complete PLUG-349

2020-09-08 12:07 UTC, tiutiunnykleasoft requested changes
Not Ok but Ok

2020-09-08 12:07 UTC, tiutiunnykleasoft commented on emspayafterpay/emspayafterpay.php
> +            'additional_addresses' => $this->getBillingAdress($cart)
getBillingAdress function not founded
the word Address must be two 'd' letters

2020-09-08 12:22 UTC, LeasoftKonstantinShapoval commented
Fixed

2020-09-08 12:48 UTC, tiutiunnykleasoft approved these changes

2020-09-09 11:39 UTC, merged